version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  build:
    machine: true
    steps:
    - checkout 
    - run: aws --version 
    - run: 
        name: Login to ECR
        command: aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 660990364978.dkr.ecr.ca-central-1.amazonaws.com
    - run: 
        name: Build Docker Image
        command: docker build --no-cache -t golang-repo -f ./Dockerfile .
    - run: 
        name: Tag Docker Image
        command: docker tag golang-repo:latest 660990364978.dkr.ecr.ca-central-1.amazonaws.com/golang-repo:latest
    - run: 
        name: Push Image to ECR
        command: docker push 660990364978.dkr.ecr.ca-central-1.amazonaws.com/golang-repo:latest

  test1:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test2:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test3:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test4:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    parallelism: 3
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    environment:
      SERVER_IMAGE: 660990364978.dkr.ecr.ca-central-1.amazonaws.com/golang-repo:latest
      CONTAINER_NAME: web-server
    machine: true
    resource_class: vijay/3x-linux-ec2
    steps:
      - checkout
      #- add_ssh_keys:
      #   fingerprints:
      #     - "6c:21:38:86:88:27:bf:de:e4:a2:63:df:59:22:dc:ea"
      - run: 
          name: Deploy Docker Image
          command: |
             docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
             aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 660990364978.dkr.ecr.ca-central-1.amazonaws.com
             docker pull $SERVER_IMAGE
             docker container run -d --restart unless-stopped --name $CONTAINER_NAME -dit -p 8080:80 $SERVER_IMAGE
      #- run: 
      #    name: Deploy Docker Image
      #    command: |
      #       ssh $AWS_EC2_SSH \<< EOF
      #       docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
      #       aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 660990364978.dkr.ecr.ca-central-1.amazonaws.com
      #       docker pull $SERVER_IMAGE
      #       docker container run -d --restart unless-stopped --name $CONTAINER_NAME -dit -p 8080:80 $SERVER_IMAGE
      #       EOF
            

workflows:
  version: 2
  main:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - test4:
          requires:
            - build

