version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  build:
    machine: true
    steps:
    - checkout 
    - run: aws --version 
    - run: 
        name: Login to ECR
        command: aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 660990364978.dkr.ecr.ca-central-1.amazonaws.com
    - run: 
        name: Build Docker Image
        command: docker build --no-cache -t golang-repo -f ./Dockerfile .
    - run: 
        name: Tag Docker Image
        command: docker tag golang-repo:latest 660990364978.dkr.ecr.ca-central-1.amazonaws.com/golang-repo:latest
    - run: 
        name: Push Image to ECR
        command: docker push 660990364978.dkr.ecr.ca-central-1.amazonaws.com/golang-repo:latest

  test1:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test2:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test3:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test

  test4:
    description: "Run tests with jest"
    docker:
      - image: circleci/node:12
    parallelism: 3
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  main:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - test4:
          requires:
            - build

